### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by spkingr** [GDquest/GDquest-art-tools#17]
How to install the plugin to Krita?
I searched and find no result. No document related.

**Comment by NathanLovato** [comment]
There's an install guide on the release page: https://github.com/GDquest/GDquest-art-tools/releases

**Comment by spkingr** [comment]
Thanks, and I also put the `gdquest_art_tools.desktop` file in the `pykrita` folder, so that the plugin appears in my Krita `settings -> configure Krita -> Python Plugin Manager` menu content list.

**Comment by alcalyn** [comment]
@spkingr thanks, moving also the `.desktop` file worked.

But the module is displayed as grey, and once enabled, I have the error:

```
krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"/home/ju/.local/share/krita/pykrita/gdquest_art_tools/__init__.py\", line 4, in <module>"
krita.scripting: "    from .GDquestArtTools import registerDocker  # noqa"
krita.scripting: "  File \"/home/ju/.local/share/krita/pykrita/gdquest_art_tools/GDquestArtTools.py\", line 21, in <module>"
krita.scripting: "    from .Infrastructure import WNode"
krita.scripting: "  File \"/home/ju/.local/share/krita/pykrita/gdquest_art_tools/Infrastructure.py\", line 8, in <module>"
krita.scripting: "    from PIL import Image, ImageOps"
krita.scripting: "ModuleNotFoundError: No module named 'PIL'"
krita.scripting: "Could not import gdquest_art_tools"
krita.scripting: Error loading plugin "gdquest_art_tools"
```

**Comment by NathanLovato** [comment]
I'd have to write a guide, you need a special local version of pillow in the addon that depends on your OS and krita version. We put up a PR to have the correct pillow and the addon come built into Krita to avoid this technical install, but we need someone to test and finish the PR for Windows.

I'll open an issue to make a guide and maybe write an install script.

**Comment by NathanLovato** [comment]
@alcalyn I just added the complete install guide to the readme: https://github.com/GDQuest/krita-batch-exporter

And I fixed the alpha release.

Sorry for not doing it earlier, I was hoping someone could help us get the Pillow library and the add-on built-into Krita itself: https://invent.kde.org/kde/krita/-/merge_requests/116

**Comment by alcalyn** [comment]
Ah nice, didn't knew about https://pypi.org/project/Pillow/#files
Thank you ! For now I used my own method, export to ORA file, then use the gimp exporter for coa tools.
But I'll try again with this exporter.
