### ISSUE TITLE
Plugin page mentions this plugin is part of Krita's official distribution, but fixes are not ported to Krita

### ISSUE THREAD

**Issue by hallarempt** [GDquest/GDquest-art-tools#67]
https://bugs.kde.org/show_bug.cgi?id=488343 tells me there are fixes in this plugin that have not been ported to the plugin in Krita's source tree, while the readme still says "Batch Exporter is now an official add-on and comes pre-installed in Krita 4.4.0." Should we remove the plugin in Krita's source tree and point to this page, or are there plans to merge fixes into Krita's version of the plugin?

**Comment by NathanLovato** [comment]
Hi Halla, long time no see! I hope it's going well for you. I just checked and we can make a PR to bring the fix to Krita, sure! With the number of repositories we manage I lose track of things, I thought things were up to date but it appears we forgot to send the last patch, sorry.

What course of action would you prefer? To keep this addon included in Krita?

**Comment by hallarempt** [comment]
Hi! Yes, I would prefer to keep this in Krita, so please make a PR on invent.kde.org. Thanks!

**Comment by NathanLovato** [comment]
On it! Gitlab is struggling to update my fork but the branch is ready and I'll have the PR up as soon as my gitlab fork syncs up with the upstream repository.

**Comment by NathanLovato** [comment]
The PR is up, so I'll close this ticket: https://invent.kde.org/graphics/krita/-/merge_requests/2168

**Comment by hallarempt** [comment]
Thanks! I merged it.
